### ISSUE TITLE
Parameter to specify the model

### ISSUE THREAD

**Issue by sakethram18** [raiyanyahya/prompt#14]
Hello, thanks for this simplistic control over CLI. Would you be able to add a parameter to choose a model and temperature if possible?

**Comment by raiyanyahya** [comment]
Yup! Thanks for the suggestion. Ill release this tomorrow.

**Comment by raiyanyahya** [comment]
hi! just added this feature and released a new version. Please update!

**Comment by raiyanyahya** [comment]
@sakethram18

**Comment by sakethram18** [comment]
Cool, thanks for the change!
