### ISSUE TITLE
Support arrow keys navigation?

### ISSUE THREAD

**Issue by jonathanlaniado** [raiyanyahya/prompt#5]
Right now during a conversation pressing the arrow keys produces `^[[A`, `^[[B`, `^[[C`, or `^[[D`.

This makes it difficult to navigate the text in a prompt horizontally.

**Comment by raiyanyahya** [comment]
You are right ...I will push a fix in the next release and let you know 😀

**Comment by raiyanyahya** [comment]
Hi this has been fixed and new release has been pushed. Please update the version of the promptcli :)
